GET http://hydralynk.local/api/payload/nodes
# Accept: text/html

###

GET http://hydralynk.local/api/payload/node/1
# Accept: text/html

###

POST http://hydralynk.local/api/payload/node
Content-Type: application/json
# Accept: text/html

{
  "payloadId": 1,
  "name": "test2",
  "value":"1",
  "type": "integer"
}

###

PUT http://hydralynk.local/api/payload/node/5
Content-Type: application/json
# Accept: text/html

{
  "value": "hello world"
}

###

DELETE http://hydralynk.local/api/payload/node/6
# Accept: text/html