GET http://hydralynk.local/api/payloads
# Accept: text/html

###

GET http://hydralynk.local/api/payload/1
# Accept: text/html

###

GET http://hydralynk.local/api/payload/1/nodes
# Accept: text/html

###

POST http://hydralynk.local/api/payload
Content-Type: application/json
# Accept: text/html

{
  "name": "Payload 1",
  "type": "json"
}

###

PUT http://hydralynk.local/api/payload/1
Content-Type: application/json
# Accept: text/html

# {
#   "name": "updated again",
#   "type": "json"
# }
{
  "type": "json"
}

###

DELETE http://hydralynk.local/api/payload/9
# Accept: text/html