<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?=$this->e($pageTitle)?></title>
  <link rel="shortcut icon" href="favicon.svg" type="image/x-icon">

  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="/css/custom.css">
  <script defer src="/js/htmx.min.js"></script>
  <?=$this->section('head-resources')?>
</head>

<body data-bs-theme="dark">
  <header>
    <?=$this->insert('shards/navigation')?>
  </header>

  <main>
    <?=$this->section('content')?>
  </main>

  <!-- <footer>
  </footer> -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/e57cdaac9a.js" crossorigin="anonymous"></script>

  <?=$this->section('body-scripts')?>
</body>

</html>